Repository neo4j/docs-http-api, pull requests merged in 2021-11, with the labels that each got.

#12 Remove prerelease attribute from component descriptor
  antora.yml
Labels: dev

#14 Change xrefs from 4.4-preview to 4.4
  modules/ROOT/pages/actions/handling-errors.adoc
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: enhancement, 4.4, cherry-pick-this-to-4.4

#15 Change xrefs from 4.4-preview to 4.4
  modules/ROOT/pages/actions/handling-errors.adoc
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: cherry-picked

#13 Add section on cluster routing capability
  modules/ROOT/pages/actions/index.adoc
  modules/ROOT/pages/actions/routing.adoc
Labels: 4.4

#16 remove discovery.adoc
  modules/ROOT/pages/discovery.adoc
Labels: 3.5
