Repository neo4j/docs-http-api, pull requests merged in 2022-11, with the labels that each got.

#56 Change external xrefs to links
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: 3.5

#57 Change external xrefs to links
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: 4.0

#58 Change external xrefs to links
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: 4.1

#59 Change external xrefs to links
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: 4.2

#60 Change external xrefs to links
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: 4.3

#61 Change external xrefs to links
  modules/ROOT/pages/discovery.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/security/index.adoc
Labels: 4.4

#62 Update packages
  package.json
  preview.yml
  publish.yml
Labels: dev

#64 Remove the CTA for NODES
  publish.yml
Labels: cherry-pick-this-forward

#65 4.4-publish-remove
  package.json
  preview.yml
  publish.yml
Labels: 4.4
