Repository neo4j/docs-http-api, pull requests merged in 2022-01, with the labels that each got.

#18 fixed typo
  modules/ROOT/pages/actions/result-format.adoc
Labels: bug, 4.2, cherry-pick-this-forward

#19 fixed typo
  modules/ROOT/pages/actions/result-format.adoc
Labels: 4.3, cherry-picked

#20 fixed typo
  modules/ROOT/pages/actions/result-format.adoc
Labels: 4.4, cherry-picked

#21 fixed typo
  modules/ROOT/pages/actions/result-format.adoc
Labels: cherry-picked, dev

#22 Add section on cluster routing capability
  modules/ROOT/pages/actions/index.adoc
  modules/ROOT/pages/actions/routing.adoc
Labels: cherry-picked

#23 Update antora.yml with new version numbers
  antora.yml
Labels: dev
