Repository neo4j/docs-http-api, pull requests merged in 2024-01, with the labels that each got.

#90 update version to 4.4.29
  antora.yml
Labels: 4.4

#94 update copyright year to 2024
  preview.yml
  publish.yml
Labels: dev, cherry-pick-this-to-5.x

#95 Merge pull request #94 from AlexicaWright/update-copyright-year
  preview.yml
  publish.yml
Labels: cherry-picked, 5.x
